# Generated by Django 5.2.13 on 2026-04-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=512)),
                ("user_prefix", models.TextField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("kind", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("finding", models.TextField()),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="findings.source",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "occurred_at"],
                        name="findings_fi_source__fc7c36_idx",
                    ),
                    models.Index(
                        fields=["source", "kind"], name="findings_fi_source__3a7599_idx"
                    ),
                ],
            },
        ),
    ]
