# Generated by Django 5.2.13 on 2026-04-20 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="uri_search",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="finding",
            name="uris",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
