# Generated by Django 5.2.13 on 2026-04-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0002_finding_uri_search_finding_uris"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="smb_cd_path",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="finding",
            name="smb_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="finding",
            name="smb_share",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
