# Generated by Django 5.2 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("findings", "0003_finding_smb_cd_path_finding_smb_host_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="plugin_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
